// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxjeeulysknibrofbvco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4amVldWx5c2tuaWJyb2ZidmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MzA0ODksImV4cCI6MjA4MzIwNjQ4OX0.mvT0f8iCoW1kYXR3rOnOsqQUJ8b544lZ2jWoAfTShCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});